apiVersion: v1
kind: Service
metadata:
  name: logger
  namespace: logger-k8s
spec:
  selector:
    app: logger
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
  externalTrafficPolicy: Cluster
